sonar.projectKey=INFO1156-GTM
sonar.projectName=INFO1156-GTM
sonar.projectVersion=0.1.0


sonar.sources=app
sonar.tests=tests


sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**,**/venv/**

sonar.python.coverage.reportPaths=coverage.xml


sonar.host.url=http://localhost:9000