sonar.projectKey=INFO1156-GTM
sonar.projectName=INFO1156-GTM
sonar.projectVersion=0.1.0

sonar.sources=gtm
sonar.tests=gtm/test

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/test/**,**/node_modules/**,**/dist/**

# Deshabilitar HTTP/2 para evitar el error "stream was reset: PROTOCOL_ERROR" al subir el reporte
sonar.ws.http.http2=false