sonar.projectKey=INFO1156-GTM
sonar.projectName=INFO1156-GTM
sonar.projectVersion=0.1.0

sonar.sources=gtm
sonar.tests=gtm/test

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/test/**,**/node_modules/**,**/dist/**