import { EstadoOrdenTrabajo, EstadoPagoOrden } from '../orden-trabajo.entity';

export type OrdenTrabajoRespuestaDto = {
  id: number;
  clienteId: string;
  rutCliente: string;
  nombreCliente: string;
  vehiculoId: string;
  patenteVehiculo: string;
  vehiculo: string;
  tipoServicio: string;
  diagnosticoInicial: string;
  mecanicoAsignado?: string;
  estado: EstadoOrdenTrabajo;
  fechaIngreso: string;
  año?: number;
  kilometraje?: number;
  costoManoObra: number;
  costoRepuestos: number;
  subtotal: number;
  porcentajeDescuento: number;
  montoDescuento: number;
  motivoDescuento: string;
  total: number;
  adelantoRequerido: number;
  totalPagado: number;
  saldoPendiente: number;
  estadoPago: EstadoPagoOrden;
  prioridad?: boolean;
};
